[package]
name = "img_to_ascii"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.20.1"
clap = {version="2.32.0", features=["yaml"]}
